resolver: lts-7.8

packages:
- '.'
- location:
    git:    https://github.com/llvm-hs/llvm-hs.git
    commit: 7d222add19129fc063b3d2d0fd190e98dc8153f9
  extra-dep: true
  subdirs:
    - 'llvm-hs'
    - 'llvm-hs-pure'

flags:
  llvm-hs:
    shared-llvm: true

extra-package-dbs: []
