resolver: lts-7.8

packages:
- '.'
- location:
    git:    https://github.com/llvm-hs/llvm-hs.git
    commit: f35803cf4e241cc7efcfbed9683fcea237f2107c
  extra-dep: true
  subdirs:
    - 'llvm-hs'
    - 'llvm-hs-pure'

flags:
  llvm-hs:
    shared-llvm: true

extra-package-dbs: []
