resolver: lts-10.2
packages:
- '.'
- location:
    git: https://github.com/llvm-hs/llvm-hs.git
    commit: d373e587431dd894255d0b4f37a5da6905fc2d60
  extra-dep: true
  subdirs:
    - llvm-hs

extra-deps:
- llvm-hs-pure-5.1.1
- llvm-hs-pretty-0.1.0.0

flags:
  llvm-hs:
    shared-llvm: true
