resolver: lts-7.8

packages:
- '.'
- location:
    git:    https://github.com/llvm-hs/llvm-hs.git
    commit: 62426d60d82a35ee87c72520d0fdb127d277552e
  extra-dep: true
  subdirs:
    - 'llvm-hs'
    - 'llvm-hs-pure'

flags:
  llvm-hs:
    shared-llvm: true

extra-package-dbs: []
